# Generated by Django 3.1.2 on 2020-10-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0001_initial'),
        ('books', '0002_auto_20201021_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_book.publisher', verbose_name='Издательство'),
            preserve_default=False,
        ),
    ]
