# Generated by Django 3.1.2 on 2020-10-24 17:02

from django.db import migrations, models


 
class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201021_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена книги'),
        ),
    ]
