# Generated by Django 3.1.2 on 2020-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.CharField(choices=[('hard', 'Твердая обложка'), ('soft', 'Мягкая обложка'), ('sup', 'Суперобложка'), ('halfsoft', 'Полумягкая обложка'), ('cloth', 'Тканевая обложка'), ('unknown', 'Не указано')], default='unknown', max_length=50, verbose_name='Вид обложки'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(default=0, max_length=20, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_pages',
            field=models.CharField(default=0, max_length=5, verbose_name='Количество страниц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_weight',
            field=models.CharField(default=0, max_length=5, verbose_name='Вес в граммах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_year',
            field=models.CharField(default=0, max_length=4, verbose_name='Год издания'),
            preserve_default=False,
        ),
    ]
