# Generated by Django 3.1.2 on 2020-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201024_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_restrictions',
            field=models.CharField(choices=[('no_restriction', '0+'), ('undersix', '6+'), ('underten', '10+'), ('undersixteen', '16+'), ('adultonly', '18+')], default='no_restriction', max_length=50, verbose_name='Возрастные ограничения'),
        ),
    ]
