# Generated by Django 3.1.2 on 2020-10-24 18:00

from django.db import migrations, models

 
class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_book_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_quantity',
            field=models.CharField(default=0, max_length=6, verbose_name='Количество книг в наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_availability',
            field=models.CharField(choices=[(0, 'Доступен для заказа'), (1, 'Нет в наличии')], default=1, max_length=20),
        ),
    ]
