# Generated by Django 3.1.2 on 2020-10-24 18:14

from django.db import migrations, models
  

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201024_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_availability',
            field=models.CharField(choices=[('yes', 'Доступен для заказа'), ('no', 'Нет в наличии')], default='no', max_length=20, verbose_name='Статус книги'),
        ),
    ]
