# Generated by Django 3.1.2 on 2020-10-25 13:15

from django.db import migrations, models
import django.db.models.deletion
  

class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0001_initial'),
        ('books', '0014_auto_20201024_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(related_name='books', to='reference_book.Author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(related_name='books', to='reference_book.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reference_book.publisher', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='reference_book.serie', verbose_name='Серия книги'),
        ),
    ]
