# Generated by Django 3.1.2 on 2020-11-05 18:14

from django.db import migrations, models
import django.db.models.deletion
 

class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0002_auto_20201101_2235'),
        ('books', '0021_auto_20201104_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(related_name='book', to='reference_book.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_serie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.serie', verbose_name='Серия книги'),
            preserve_default=False,
        ),
    ]
