# Generated by Django 3.1.2 on 2020-11-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_book', '0002_auto_20201101_2235'),
        ('books', '0022_auto_20201105_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='reference_book.publisher', verbose_name='Издательство'),
            preserve_default=False,
        ),
    ]
