# Generated by Django 3.1.2 on 2020-11-07 21:12

from django.db import migrations, models

 
class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20201105_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_adding_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
    ]
