# Generated by Django 3.1.2 on 2020-11-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('zip', models.IntegerField(blank=True, verbose_name='Индекс')),
                ('second_address', models.CharField(blank=True, max_length=100, verbose_name='Второй адрес')),
                ('third_address', models.CharField(blank=True, max_length=100, verbose_name='Третий адрес')),
                ('additional_information', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
