# Generated by Django 3.1.2 on 2020-11-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productincart_book'),
        ('conf_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.cart'),
        ),
    ]
