# Generated by Django 3.1.2 on 2020-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_order', '0004_auto_20201130_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Доставка', 'Доставка'), ('Отменен', 'Отменен'), ('Выполнен', 'Выполнен')], default='В обработке', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
