# Generated by Django 3.1.2 on 2020-11-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_book_book_picture'),
        ('orders', '0003_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='books.book'),
            preserve_default=False,
        ),
    ]
