# Generated by Django 3.1.2 on 2020-12-01 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_book_book_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_productincart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_in_cart', to='books.book'),
        ),
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together={('cart', 'book')},
        ),
    ]
